name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install Deps
      run: npm install --only=prod --no-optional
    
    - name: Build page
      run: npm run build
      
    - name: Deploy using rsync
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: build/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: golfersflyby.com
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
